CREATE SCHEMA IF NOT EXISTS OtoRes ; 
USE OtoRes;

CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
surname VARCHAR(100) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
phone VARCHAR(20) NOT NULL,
role ENUM('user', 'moderator', 'admin') NOT NULL DEFAULT 'user',
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vehicles(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
plate VARCHAR(20) NOT NULL UNIQUE,
brand VARCHAR(100) NOT NULL,
model VARCHAR(200) NOT NULL,
year INT NOT NULL,
chassis_no VARCHAR(100) NOT NULL UNIQUE,
FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS reservations(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
vehicle_id INT NOT NULL,
res_date DATE NOT NULL,
res_time TIME NOT NULL,
description TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (vehicle_id) REFERENCES vehicle(id)
);
